### ISSUE TITLE
Did not fully release the dataset

### ISSUE THREAD

**Issue by hdvvip** [dair-ai/emotion_dataset#2]
The dataset in the download link in README: https://www.dropbox.com/s/607ptdakxuh5i4s/merged_training.pkl
has only 6 emotions, not 8 emotions as described in the paper.
The dataset size is also much smaller.
Please double-check the dataset download link

**Comment by omarsar** [comment]
Hi @hdvvip. The dataset released is a preprocessed six emotion variant released for educational and research purposes.
