### ISSUE TITLE
Data files are no longer accessible

### ISSUE THREAD

**Issue by albertvillanova** [dair-ai/emotion_dataset#5]
Your data files are no longer accessible at Dropbox.

Are you aware of this issue?

Alternatively, we could host them on the Hugging Face Hub if you agree, as you already point to the Hugging Face loading script in your README: https://huggingface.co/datasets/emotion

**Comment by aupuzikov** [comment]
so, thnx to @imatiach-msft and his PR to ml-wrappers it seems using "SetFit/emotion" instead of "emotion" works as old one. looks like this workaround can help

**Comment by ghadesi** [comment]
Hi programmers :), the problem is not fixed yet!

**Comment by omarsar** [comment]
A new link is provided to download the dataset. Sorry for the inconvenience.

**Comment by abbascs** [comment]
Hi dear @omarsar
Thank you for sharing
Unfortunately I got this error:

> Item Unavailable
> The owner stopped sharing, or you do not have permission to open this item.

**Comment by omarsar** [comment]
> Hi dear @omarsar Thank you for sharing Unfortunately I got this error:
> 
> > Item Unavailable
> > The owner stopped sharing, or you do not have permission to open this item.

Can you try again and let me know if you can access it now? @abbascs

**Comment by abbascs** [comment]
Yep 
That's works 
Thank you

**Comment by krishnareddyML** [comment]
Today I am seeing same issue while downloading emotion dataset
`from datasets import load_dataset
 emotions = load_dataset("emotion")`

FileNotFoundError: Couldn't find file at https://www.dropbox.com/s/1pzkadrvffbqw6o/train.txt?dl=1

**Comment by abbascs** [comment]
!pip install datasets==2.9.0

from datasets import load_dataset
emotions_ds = load_dataset("emotion")

this work for me

**Comment by julien-c** [comment]
Hi @omarsar, sorry about piggybacking on this thread... would you be interested in us transfering the HF repo for this dataset (https://huggingface.co/datasets/emotion) to your org on hf.co ? 

That would be cleaner and would bring clearer visibility/usage on this dataset!

cc @osanseviero @albertvillanova

**Comment by albertvillanova** [comment]
The data files can also be hosted on the Hugging Face Hub, instead of in Dropbox... :wink: 

You could also create your organization namespace, for example "dairai": https://huggingface.co/dairai
Or you could host the dataset under your personal namespace: https://huggingface.co/omarsar

**Comment by julien-c** [comment]
@albertvillanova oh but i think the data files are already in the repo since https://huggingface.co/datasets/emotion/discussions/4, no?

**Comment by julien-c** [comment]
(contributed by community member @mainpyp ❤️)

**Comment by albertvillanova** [comment]
You are right, @julien-c: I made that PR... :sweat_smile:

**Comment by omarsar** [comment]
Thanks, @julien-c, @albertvillanova.

That makes perfect sense to me. I don't have an organization on HF yet. Could someone help create this for the DAIR.AI organization? We are planning on putting more stuff there soon so this sounds like a good idea now.

**Comment by albertvillanova** [comment]
I'm taking care of this.

**Comment by albertvillanova** [comment]
We have created the DAIR.AI organization: https://huggingface.co/dair-ai
- @omarsar you are administrator of that organization

We have also transferred the "emotion" dataset under this organization: https://huggingface.co/datasets/dair-ai/emotion

**Comment by abbascs** [comment]
Hello again.
How can I have Tweet-id of this dataset? @omarsar
